default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  user: h0
  password: "kjkjirf"

development:
  database: trident
  <<: *default

test:
  database: trident_test
  <<: *default

production:
  database: trident
  <<: *default
