default: &default
  adapter: postgresql
  encoding: unicode
  database: trident
  host: localhost
  pool: 5
  user: postgres
  password: mysecretpassword

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default